#S3 BUCKETS CONFIG

AWS_ACCESS_KEY_ID = 'AKIATFFCEOXAR3PPU3HP'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'kpi-chat'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_S3_SIGNATURE_VERSION = 's3v4'
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_QUERYSTRING_AUTH = False